### ISSUE TITLE
"Cannot read properties of undefined..."

### ISSUE THREAD

**Issue by jeranon** [Dalvii/plex-library-export#5]
`E:\Downloads\plex-library-export-main>npm run start`
`> plex-library-export@1.0.0 start`
`> node main.js`

`E:\Downloads\plex-library-export-main\main.js:106
    const content = json.MediaContainer.Directory == undefined ? json.MediaContainer.Video : json.MediaContainer.Directory;
                                        ^
`
`TypeError: Cannot read properties of undefined (reading 'Directory')`
`    at get (E:\Downloads\plex-library-export-main\main.js:106:41)`
`    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

For the life of me, I can't figure out what I'm doing wrong. I've followed the directions in the readme, but I'm stuck here.

**Comment by DrKain** [comment]
Not sure if you're still looking for help, but this error means the token you entered is invalid.  
Assuming @Dalvii is still active, the PR above should log a message when this happens.

**Comment by jeranon** [comment]
I think perhaps I mixed up the token for plex.tv vs my 192.168..... token. I tried it today works like a charm.

Closing this now, and I appreciate the insight!
